version: 1
formatters:
  plain:
    format: '%(asctime)s %(levelname)s %(name)s %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    formatter: plain
root:
  level: INFO
  handlers: [console]
